provider "aws" {
  region = "us-east-1" # Change to your region
}

# -------------------------------------------------------------------
# DATA SOURCES (Optional, but good for validation if you want)
# -------------------------------------------------------------------
data "aws_vpc" "existing" {
  id = "vpc-0f238901bc3467b62"
}

data "aws_subnet" "subnet_a" {
  id = "subnet-08d90b90e9b121c7e"
}

data "aws_subnet" "subnet_b" {
  id = "subnet-01d84fc63df0a696c"
}

# -------------------------------------------------------------------
# 1. LOAD BALANCER (ALB)
# -------------------------------------------------------------------
resource "aws_lb" "app_alb" {
  name               = "my-app-alb"
  load_balancer_type = "application"

  # ALB needs to be in at least 2 subnets across different AZs
  subnets = [data.aws_subnet.subnet_a.id, data.aws_subnet.subnet_b.id]

  # Ensure the ALB has a Security Group. 
  # If you want to create one automatically:
  security_groups = [aws_security_group.alb_sg.id]

  tags = {
    Name = "MyApp-ALB"
  }
}

# Create a dedicated Security Group for the ALB itself (optional but recommended)
resource "aws_security_group" "alb_sg" {
  name        = "ALB-SG-AutoGenerated"
  vpc_id      = data.aws_vpc.existing.id
  description = "Allow inbound traffic to ALB"

  ingress {
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"] # Allow anyone to hit the ALB
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name = "ALB-SG"
  }
}

# -------------------------------------------------------------------
# 2. TARGET GROUP
# -------------------------------------------------------------------
resource "aws_lb_target_group" "app_tg" {
  name     = "my-app-target-group"
  port     = 80 # Port where your app runs (e.g., Nginx/Apache on EC2)
  protocol = "HTTP"
  vpc_id   = data.aws_vpc.existing.id

  health_check {
    path     = "/" # Health check path
    port     = "traffic-port"
    protocol = "HTTP"
    matcher  = "200" # Expect HTTP 200 OK
    timeout  = 5
    interval = 10
  }

  tags = {
    Name = "MyApp-TG"
  }
}

# -------------------------------------------------------------------
# 3. EC2 INSTANCES (Using your AMI)
# We use a for_each or count to create 2 instances.
# Note: Terraform will place them in the VPC automatically based on subnet assignment.
# We'll alternate subnets if possible, but since we only have 2 static subnets, 
# we can assign one instance per subnet explicitly for high availability.
# -------------------------------------------------------------------

resource "aws_instance" "app_server_1" {
  ami           = "ami-07ac293eb06a17539"
  instance_type = "t3.medium"                  # Change to desired size (e.g., t3.small)
  subnet_id     = data.aws_subnet.subnet_a.id # Place in Subnet A

  vpc_security_group_ids = [data.aws_security_group.existing_sg.id]

  tags = {
    Name = "Ship-Date-Engine-1a"
  }
}

resource "aws_instance" "app_server_2" {
  ami           = "ami-07ac293eb06a17539"
  instance_type = "t3.medium"                  # Change to desired size
  subnet_id     = data.aws_subnet.subnet_b.id # Place in Subnet B

  vpc_security_group_ids = [data.aws_security_group.existing_sg.id]

  tags = {
    Name = "Ship-Date-Engine-1b"
  }
}

# Data source for the existing Security Group ID you provided
data "aws_security_group" "existing_sg" {
  id = "sg-0c664a06372836c3f"
}

# -------------------------------------------------------------------
# 4. ATTACH INSTANCES TO TARGET GROUP
# -------------------------------------------------------------------
resource "aws_lb_target_group_attachment" "tg_attach_1" {
  target_group_arn = aws_lb_target_group.app_tg.arn
  target_id        = aws_instance.app_server_1.id
  port             = 80 # Port on the EC2 instance to forward to
}

resource "aws_lb_target_group_attachment" "tg_attach_2" {
  target_group_arn = aws_lb_target_group.app_tg.arn
  target_id        = aws_instance.app_server_2.id
  port             = 80 # Port on the EC2 instance to forward to
}

# -------------------------------------------------------------------
# 5. LOAD BALANCER LISTENER (HTTP)
# -------------------------------------------------------------------
resource "aws_lb_listener" "app_http" {
  load_balancer_arn = aws_lb.app_alb.arn
  port              = 80
  protocol          = "HTTP"

  default_action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.app_tg.arn
  }
}

# -------------------------------------------------------------------
# OUTPUTS
# -------------------------------------------------------------------
output "alb_dns_name" {
  value = aws_lb.app_alb.dns_name
}

output "instance_ips" {
  value = [aws_instance.app_server_1.private_ip, aws_instance.app_server_2.private_ip]
}
